# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38808c2071fdb4de78f3642366562746f5cbd2ec4a406c9e194b80c44566c858f593a5dd5f4718d45caf0eaf10f834119ca36fd6dc1d429ee36a7e90acc58fd9

test:
  secret_key_base: 131d81717903551dbc02c25570b32a3d22d7afac3da44741d3622b01cb988ca8f10f44c9365f3f4bdf4714c9c19452393fb92fb1b940d4b4fc40f0ac9fed4e00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
